### ISSUE TITLE
crash if chose folder when mobile connection is on

### ISSUE THREAD

**Issue by muhammadarif1** [limitedeternity/MediaServer#1]
when ever i want to use this app it always crash if i use mobile connection
but it works as wells when i am use wifi

**Comment by muhammadarif1** [comment]
Pleaee give a feedback sjr

**Comment by limitedeternity** [comment]
![image](https://user-images.githubusercontent.com/24318966/58747722-d7eb2f80-8477-11e9-9a4e-1a711236cd7b.png)

**Comment by limitedeternity** [comment]
Well, could you attach logs from logcat here, @muhammadarif1 ?

**Comment by muhammadarif1** [comment]
```Fatal signal 6 (SIGABRT), code -6 in tid 11144 (ty.media_server)```
Tell me if  you need more sir

**Comment by limitedeternity** [comment]
Sure I do. I need as much info as possible.
Sounds like app terminates itself, that's weird oO

**Comment by limitedeternity** [comment]
@muhammadarif1 I've rebuilt apk, could you remove existing application and test the new one, please?

**Comment by muhammadarif1** [comment]
Yes,

**Comment by muhammadarif1** [comment]
Just try a new realease same promblem still appear,and i  can't find a right logcat using my android device or adb

**Comment by muhammadarif1** [comment]
https://youtu.be/cTGTrh0YPB0
Crash recording

I just can found this
[logcat_06-02-2019_04-47-50.txt](https://github.com/limitedeternity/MediaServer/files/3244239/logcat_06-02-2019_04-47-50.txt)

**Comment by limitedeternity** [comment]
Android version?

**Comment by muhammadarif1** [comment]
5.1

**Comment by limitedeternity** [comment]
I can conclude that that's something wrong with your modem firmware or mobile operator who restricts port forwarding even on local network.
Any way, the "other" device should be on the same network as you, so mobile one is not suitable for that. Prefer using mobile hotspot or wifi.
Closing.

**Comment by muhammadarif1** [comment]
Not a bug?

**Comment by limitedeternity** [comment]
Definitely not

**Comment by muhammadarif1** [comment]
But it crash

**Comment by limitedeternity** [comment]
And I can't get it crashed on mobile network.
